---
name: bosh

releases:
- name: bosh
  url: http://bosh.io/d/github.com/cloudfoundry/bosh?v=256.1
  sha1: bc1538d32cd030216ac39723d363b6dc70bdcc55
- name: bosh-photon-cpi
  url: file:///CPI_RELEASE
  sha1: CPI_SHA1

resource_pools:
- name: vms
  network: default
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3232.1
    sha1: 169df93e3e344cd84ac6ef16d76dd0276e321a25
  cloud_properties:
    vm_flavor: core-200
    disk_flavor: core-200
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"


disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties:
    disk_flavor: core-200

networks:
- name: default
  type: manual
  subnets:
  - range: BOSH_DEPLOYMENT_NETWORK_SUBNET
    gateway: BOSH_DEPLOYMENT_NETWORK_GW
    dns: [BOSH_DEPLOYMENT_NETWORK_DNS]
    cloud_properties:
      network_id: BOSH_DEPLOYMENT_NETWORK_ID

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: powerdns, release: bosh}
  - {name: cpi, release: bosh-photon-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - {name: default, static_ips: [BOSH_DEPLOYMENT_NETWORK_IP]}

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    redis:
      password: redis-password
      listen_addresss: 127.0.0.1
      address: 127.0.0.1

    blobstore:
      address: BOSH_DEPLOYMENT_NETWORK_IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: cpi
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: BOSH_DEPLOYMENT_USER, password: BOSH_DEPLOYMENT_PASSWORD}
      resurrector_enabled: true

    dns:
      address: 127.0.0.1
      db: *db

    photon: &photon
      target: http://PHOTON_CTRL_IP:9000
      user: PHOTON_USER
      password: PHOTON_PASSWD
      ignore_cert: PHOTON_IGNORE_CERT
      tenant: PHOTON_TENANT
      project: PHOTON_PROJ_ID

    agent: {mbus: "nats://nats:nats-password@BOSH_DEPLOYMENT_NETWORK_IP:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: cpi, release: bosh-photon-cpi}
  mbus: "https://mbus:mbus-password@BOSH_DEPLOYMENT_NETWORK_IP:6868"

  properties:
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore:
      provider: local
      options:
        blobstore_path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp
    photon: *photon
